### ISSUE TITLE
 go get github.com/blockfreight/go-bftx appears to fail

### ISSUE THREAD

**Issue by arsen3d** [blockfreight/blockfreight-alpha#1]
Arsens-MacBook-Pro:~ arsenyeremin$ go version
go version go1.9.2 darwin/amd64
Arsens-MacBook-Pro:~ arsenyeremin$ curl https://glide.sh/get | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4201  100  4201    0     0  17694      0 --:--:-- --:--:-- --:--:-- 17800
glide needs environment variable $GOPATH. Set it before continue.
Fail to install glide
Arsens-MacBook-Pro:~ arsenyeremin$ brew install glide
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
Arsens-MacBook-Pro:~ arsenyeremin$ brew install glide
==> Installing dependencies for glide: go
==> Installing glide dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.8.sierra.bottle.tar.gz

curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "go"
Download failed: https://homebrew.bintray.com/bottles/go-1.8.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://storage.googleapis.com/golang/go1.8.src.tar.gz

curl: (6) Could not resolve host: storage.googleapis.com
Trying a mirror...
==> Downloading https://fossies.org/linux/misc/go1.8.src.tar.gz

curl: (6) Could not resolve host: fossies.org
Error: Failed to download resource "go"
Download failed: https://fossies.org/linux/misc/go1.8.src.tar.gz
Arsens-MacBook-Pro:~ arsenyeremin$ brew install glide
Updating Homebrew...
==> Installing dependencies for glide: go
==> Installing glide dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.8.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring go-1.8.sierra.bottle.tar.gz
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.8: 7,017 files, 281.6MB
==> Installing glide 
==> Downloading https://homebrew.bintray.com/bottles/glide-0.12.3.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring glide-0.12.3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/glide/0.12.3: 6 files, 10MB
Arsens-MacBook-Pro:~ arsenyeremin$ go get github.com/blockfreight/go-bftx
package github.com/blockfreight/go-bftx: no Go files in /Users/arsenyeremin/go/src/github.com/blockfreight/go-bftx
Arsens-MacBook-Pro:~ arsenyeremin$ cd $GOPATH/src/github.com/blockfreight/go-bftx
-bash: cd: /src/github.com/blockfreight/go-bftx: No such file or directory

**Comment by gianfelipe93** [comment]
Hi @arsen3d 

Have you set the $GOPATH variable ?

**Comment by arsen3d** [comment]
@gianfelipe93 I did not.
