### ISSUE TITLE
If GOPATH is not set then "bftx node start" fails

### ISSUE THREAD

**Issue by billc3012** [blockfreight/blockfreight-alpha#27]
When GO is installed on a clean linux install the GOPATH environment variable may be null and links to the bftx config file cannot be setup.  The documentation should be updated to warn users that this should be done.

Updated MD file follows

[README.md.txt](https://github.com/blockfreight/go-bftx/files/2355905/README.md.txt)

**Comment by jsmith-dev** [comment]
Hi @billc3012 

Thank you so much for this bug-report.

Will assign it to myself.

**Comment by billc3012** [comment]
Where to  next ?

**Comment by jsmith-dev** [comment]
I added an installer (one-line install) script. Will start to embed the logic in to there (in that file).

https://github.com/blockfreight/go-bftx#installation

Glad you got Golang running on your install machine.
