### ISSUE TITLE
python test command not working, while python is installed as evident further in log

### ISSUE THREAD

**Issue by arsen3d** [blockfreight/blockfreight-alpha#3]
> imac5k2015:bftx arsen$ ./bftx total

...........................................
Blockfreight™ Go App
Address tcp://127.0.0.1:46658
BFT Implementation:  socket
...........................................

-> blockfreight result: Total BF_TX on BD: 0
imac5k2015:bftx arsen$ ./bftx python 

...........................................
Blockfreight™ Go App
Address tcp://127.0.0.1:46658
BFT Implementation:  socket
...........................................

chdir ./lib/pkg/python/: no such file or directory
chdir ./lib/pkg/python/: no such file or directory
2017/10/28 22:54:06 chdir ./lib/pkg/python/: no such file or directory
imac5k2015:bftx arsen$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by jsmith-dev** [comment]
@gianfelipe93 - can you review this?

**Comment by gianfelipe93** [comment]
@arsen3d The python functions were removed from the source code, so we do not have this problem anymore.

Thanks for reporting.
