### ISSUE TITLE
BFTX command not global

### ISSUE THREAD

**Issue by martinhalford** [blockfreight/blockfreight-alpha#4]
Hi All,

I followed the instructions for installation but the BFTX command is not global. Need to run commands as:

./cmd/bftx/bftx [command] [args...]

from 

go/src/github.com/blockfreight/go-bftx 

in order to execute.

Running on macOS High Sierra Version 10.13.2 (17C88)

Thanks,
...Martin

**Comment by jsmith-dev** [comment]
Thank you @martinhalford for reporting this.

We will investigate and come back with a suggestion / fix or an update release.

**Comment by gianfelipe93** [comment]
Hi @martinhalford ,

Importantly, in the go-bftx tutorial users need to add **$GOPATH/bin** to the **PATH** environment variable. There is an example here: 

https://github.com/golang/go/wiki/SettingGOPATH

I believe that after that, bftx and bftnode will be global.
